import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { load } from '../src/func';

export default function Home() {

  const [blogList, setBlogList] = useState([]);
  const [refresh, setRefresh] = useState(true);


  const loadBlogs = () => {
    load().then((e) => {
      setBlogList(e.blogs);
    });
  }

  useEffect(() => {
    if (!refresh) return;

    setRefresh(false);

    loadBlogs();
  });
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="text-gray-600 body-font overflow-hidden md:mx-52 ">
        <h2 className=" text-5xl text-gray-900 font-bold ">Latest Blogs</h2>
        <div className="container px-5 py-24 mx-auto">
          <div className="-my-8 divide-y-2 divide-gray-100">

            <h2>blogCount = {blogList.length}</h2>
            {/* {console.log(typeof(blogList[0][0]))} */}
            

          { blogList.map((blog) => {
           return <div className="py-8 flex flex-wrap md:flex-nowrap" key={ blog['1']}>
              <div className="md:w-64 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
                <span className="font-semibold title-font text-gray-700">
                  Category
                </span>
              </div>
              <div className="md:flex-grow">
                <h2 className="text-2xl font-medium text-gray-900 title-font mb-2">
                  {blog[1]}
                </h2>
                <p className="leading-relaxed">
                  {blog['content']}
                </p>
                <a className="text-indigo-500 inline-flex items-center mt-4">
                  Learn More about 
                  <svg
                    className="w-4 h-4 ml-2"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth="2"
                    fill="none"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <path d="M5 12h14"></path>
                    <path d="M12 5l7 7-7 7"></path>
                  </svg>
                </a>
              </div>
            </div>
          }) }
            
            
          </div>
        </div>
      </section>
    </>
  );
}
